### ISSUE TITLE
Release 0.2.0 by assigning the tag "0.2.0"

### ISSUE THREAD

**Issue by neoneye** [OAuthSwift/OAuthSwiftAlamofire#10]
I'm unable to make a dependency to OAuthSwiftAlamofire's version number.

Because the last release is 0.1.0 from Oct 6, 2016, which doesn't include newer commits.
https://github.com/OAuthSwift/OAuthSwiftAlamofire/releases

Thank you for a great framework.

**Comment by phimage** [comment]
I will check #12 and then make a release

And also make a swift 4 release , 1.0.0

**Comment by phimage** [comment]
🎉  Congrats

 🚀  OAuthSwiftAlamofire (0.2.0) successfully published
 📅  June 26th, 17:04
 🌎  https://cocoapods.org/pods/OAuthSwiftAlamofire
 👍  Tell your friends!
