### ISSUE TITLE
No longer compatible with OAuthSwift (2.0.0)

### ISSUE THREAD

**Issue by garyhooper** [OAuthSwift/OAuthSwiftAlamofire#21]
Using OAuthSwiftAlamofire (0.2.0) with OAuthSwift (2.0.0) (and Xcode 10.2.1/Swift 5), I encounter a compiler error in OAuthSwiftRequestAdaptor, line 80: parameters do not match  oauth2Swift.renewAccessToken.

**Comment by phimage** [comment]
Hi
Yes it not compatible.
I make breaking change OAuthSwift

This project work only with old version see https://github.com/OAuthSwift/OAuthSwiftAlamofire/blob/master/Cartfile.resolved

I am waiting for official Alamofire 5.0.0 version (not beta)
But If someone want PR an intermediate version...

**Comment by phimage** [comment]
@garyhooper I make in master a beta version with Alamofire 5 beta and OAuthSwift 2
`adapter` has been renamed to `interceptor` and must be passed in session creation or in request

**Comment by garyhooper** [comment]
Is it tagged, or just the master?

**Comment by phimage** [comment]
I make a 1.0.0beta tag

**Comment by phimage** [comment]
now master branch is linked with oauthswift2.1.0 for xcode11
