### ISSUE TITLE
How can I get access token wihtout passing authorization URL?

### ISSUE THREAD

**Issue by hadwanihardik** [OAuthSwift/OAuthSwiftAlamofire#25]
Hello there,

I want to implement Oauth2.0 with following parameters
client secret,
client key,
access token URL.
I am attaching screen shot for the same.
I see your code is asking for authorization url. 

I tested api in postman it works fine.

Can you please let me know how I can achieve using your library?

**Here is screenshot for request**
<img width="617" alt="Screen Shot 2019-12-23 at 10 52 26 AM" src="https://user-images.githubusercontent.com/5634693/71337683-aa301a00-2572-11ea-85e8-596f8185129d.png">

**Here is screenshot for Response**

<img width="520" alt="Screen Shot 2019-12-23 at 10 53 30 AM" src="https://user-images.githubusercontent.com/5634693/71337691-adc3a100-2572-11ea-99a9-1a68271c9482.png">

**Comment by phimage** [comment]
I think the issue is more for OAuthSwift. There is a template issue with question that I need answer to understand
