### ISSUE TITLE
Xcode8.3.1 warnings

### ISSUE THREAD

**Issue by neoneye** [OAuthSwift/OAuthSwiftAlamofire#7]
There are these 4 warnings. Please fix

    OAuthSwiftError.swift:98:58: String interpolation produces a debug description for an optional value; did you mean to make this explicit?
    String+OAuthSwift.swift:88:24: Forced cast from 'CFString?' to 'String' only unwraps and bridges; did you mean to use '!' with 'as'?
    String+OAuthSwift.swift:50:30: Conditional downcast from 'NSString?' to 'String' is a bridging conversion; did you mean to use 'as'?
    String+OAuthSwift.swift:50:60: Conditional downcast from 'NSString?' to 'String' is a bridging conversion; did you mean to use 'as'?

Thank you for this awesome framework

**Comment by phimage** [comment]
wrong project
OAuthSwift/OAuthSwift not OAuthSwift/OAuthSwiftAlamofire

**Comment by neoneye** [comment]
Sorry Eric
